keys:
    telegram_token: =====key=====
conn_params:
    clean: true
    updater_workers: 8
    timeout: 10
    bootstrap_retries: -1
    poll_interval: 0.5
    read_latency: 2.0

features:
    anime_search:
        enabled: true
        commands_gelbooru:
            - gelbooru
            - gel
        commands_yandere:
            - a
            - yandere
            - yan
        proxy:
            user: username
            password: password
            server: proxy.example.com:1080
            
    embed:
        enabled: true
        commands: 
            - fap
        path: userdata/
        launchpad_path: resources/embed/launchpad.mp4
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .webp

    glitch:
        enabled: true
        commands: 
            - glitch
        path: userdata/
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .bmp 
            - .webp

    google_search:
        enabled: true
        commands_image:
            - google
            - img
        commands_gif:
            - gif
            - gifs

    jpeg:
        enabled: true
        commands:
            - jpeg
        path: userdata/
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .bmp
            - .webp

    kek:
        enabled: true
        commands: 
            - kek
        path: userdata/
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .bmp 
            - .webp
            - .gif
            - .mp4

    leetspeak:
        enabled: true
        commands: 
            - leet
        leet_dictionary: resources/leetdict.txt

    lego:
        enabled: true
        commands: 
            - lego
        path: userdata/
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .bmp
            - .gif
            - .webp

    liquid:
        enabled: true
        commands: 
            - liq
        path: userdata/

    logging:
        enabled: true
        path: userdata/

    meme:
        enabled: true
        commands: 
            - meme
            - memos
        path: userdata/
        fonts:
            impact:
                name: impact
                path: resources/impact.ttf
            lobster:
                name: lobster
                path: resources/lobster.ttf
            comic:
                name: comic
                path: resources/comic.ttf
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .webp

    merch:
        enabled: true
        commands: 
            - merch
        path: userdata/
        resources_path: resources/merch/
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .webp

    nya:
        enabled: true
        commands: 
            - nya
        path: userdata/nya/
        
    nyameme:
        enabled: true
        commands_nyameme:
            - nm
            - nyameme
        commands_animeme:
            - am
            - animeme
        path: userdata/
        nyapath: userdata/nya/
        extensions:
            - .jpg
            - .jpeg
            - .png
        
    palette:
        enabled: true
        commands:
            - palette
            - colors
        path:
            userdata/
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .webp
            - .bmp
            - .gif

    quote:
        enabled: true
        commands: 
            - quote
            - q
        path: userdata/
        resources_path: resources/quote/
        font: resources/gothic.ttf

    rate:
        enabled: true
        commands:
            - rate
            
    reverse:
        enabled: true
        commands: 
            - reverse
            - rev
        path: userdata/

    roll:
        enabled: true
        commands:
            - roll
            
    system:
        enabled: true
        commands: 
            - system
    tts:
        enabled: true
        commands: 
            - say
        path: userdata/
        
    zalgo:
        enabled: true
        commands:
            - zalgo
